# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb64ce0cac955c4985208e93057227071a6073a6b1285e28dcac4778f9073cafe788f91626fad9abef38c9e9a49bf7cbfee8fd3cc97cfab2576e61fc37c2b2a

test:
  secret_key_base: 12a82bab525eed42e62e0b50f2e310c21bdf70e8eccc85624dbbfa97d64a9a8e07f95d77d88493029585fdaf5a86300877b8cf8adcfcfc9ad5917dfc2a1582ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
